const imageData = [
    {
        "id": 216,
        "crop": "tomato",
        
        
    },
    {
        "id": 20,
        "name": "basil",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Basil",
        "created_at": "2013-03-19T01:30:25.222Z",
        "updated_at": "2019-05-02T09:32:30.641Z",
        "slug": "basil",
        "parent_id": null,
        "plantings_count": 132,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 142,
        "median_days_to_first_harvest": 51,
        "median_days_to_last_harvest": 54
    },
    {
        "id": 113,
        "name": "lettuce",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Lettuce",
        "created_at": "2013-03-19T01:30:27.123Z",
        "updated_at": "2019-04-29T10:36:06.359Z",
        "slug": "lettuce",
        "parent_id": null,
        "plantings_count": 124,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 104,
        "median_days_to_first_harvest": 37,
        "median_days_to_last_harvest": 105
    },
    {
        "id": 37,
        "name": "carrot",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Carrot",
        "created_at": "2013-03-19T01:30:25.578Z",
        "updated_at": "2019-01-12T05:21:42.306Z",
        "slug": "carrot",
        "parent_id": null,
        "plantings_count": 101,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 130,
        "median_days_to_first_harvest": 88,
        "median_days_to_last_harvest": 98
    },
    {
        "id": 22,
        "name": "bean",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Common_bean",
        "created_at": "2013-03-19T01:30:25.258Z",
        "updated_at": "2017-11-10T16:32:02.160Z",
        "slug": "bean",
        "parent_id": null,
        "plantings_count": 78,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 65,
        "median_days_to_first_harvest": 90,
        "median_days_to_last_harvest": null
    },
    {
        "id": 146,
        "name": "pea",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Pea",
        "created_at": "2013-03-19T01:30:27.985Z",
        "updated_at": "2019-01-12T09:37:12.047Z",
        "slug": "pea",
        "parent_id": null,
        "plantings_count": 76,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 91,
        "median_days_to_first_harvest": 79,
        "median_days_to_last_harvest": 144
    },
    {
        "id": 64,
        "name": "cucumber",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Cucumbers",
        "created_at": "2013-03-19T01:30:26.178Z",
        "updated_at": "2018-06-11T00:11:29.455Z",
        "slug": "cucumber",
        "parent_id": null,
        "plantings_count": 67,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 98,
        "median_days_to_first_harvest": 81,
        "median_days_to_last_harvest": 139
    },
    {
        "id": 231,
        "name": "zucchini",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Zucchini",
        "created_at": "2013-03-19T01:30:30.284Z",
        "updated_at": "2018-06-21T02:05:48.613Z",
        "slug": "zucchini",
        "parent_id": 509,
        "plantings_count": 65,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 113,
        "median_days_to_first_harvest": 93,
        "median_days_to_last_harvest": null
    },
    {
        "id": 102,
        "name": "kale",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Kale",
        "created_at": "2013-03-19T01:30:26.855Z",
        "updated_at": "2018-09-07T23:13:02.335Z",
        "slug": "kale",
        "parent_id": 477,
        "plantings_count": 63,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 187,
        "median_days_to_first_harvest": 27,
        "median_days_to_last_harvest": 31
    },
    {
        "id": 140,
        "name": "onion",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Onions",
        "created_at": "2013-03-19T01:30:27.618Z",
        "updated_at": "2019-01-08T22:27:55.430Z",
        "slug": "onion",
        "parent_id": null,
        "plantings_count": 62,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 210,
        "median_days_to_first_harvest": 252,
        "median_days_to_last_harvest": 325
    },
    {
        "id": 30,
        "name": "broccoli",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Broccoli",
        "created_at": "2013-03-19T01:30:25.441Z",
        "updated_at": "2019-01-11T09:58:03.843Z",
        "slug": "broccoli",
        "parent_id": 476,
        "plantings_count": 60,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 118,
        "median_days_to_first_harvest": 103,
        "median_days_to_last_harvest": 133
    },
    {
        "id": 23,
        "name": "beet",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Beet",
        "created_at": "2013-03-19T01:30:25.279Z",
        "updated_at": "2019-02-03T10:15:11.266Z",
        "slug": "beet",
        "parent_id": null,
        "plantings_count": 59,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 183,
        "median_days_to_first_harvest": null,
        "median_days_to_last_harvest": null
    },
    {
        "id": 24,
        "name": "bell pepper",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Bell_pepper",
        "created_at": "2013-03-19T01:30:25.298Z",
        "updated_at": "2018-12-17T23:46:53.106Z",
        "slug": "bell-pepper",
        "parent_id": 307,
        "plantings_count": 59,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 238,
        "median_days_to_first_harvest": 105,
        "median_days_to_last_harvest": 129
    },
    {
        "id": 87,
        "name": "garlic",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Garlic",
        "created_at": "2013-03-19T01:30:26.606Z",
        "updated_at": "2019-01-19T06:33:42.028Z",
        "slug": "garlic",
        "parent_id": null,
        "plantings_count": 59,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 191,
        "median_days_to_first_harvest": 224,
        "median_days_to_last_harvest": 200
    },
    {
        "id": 199,
        "name": "spinach",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Spinach",
        "created_at": "2013-03-19T01:30:29.579Z",
        "updated_at": "2019-04-21T06:13:07.101Z",
        "slug": "spinach",
        "parent_id": null,
        "plantings_count": 59,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 112,
        "median_days_to_first_harvest": 107,
        "median_days_to_last_harvest": 137
    },
    {
        "id": 203,
        "name": "strawberry",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Strawberry",
        "created_at": "2013-03-19T01:30:29.725Z",
        "updated_at": "2018-04-25T03:51:12.180Z",
        "slug": "strawberry",
        "parent_id": null,
        "plantings_count": 59,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 15,
        "median_days_to_first_harvest": 92,
        "median_days_to_last_harvest": null
    },
    {
        "id": 143,
        "name": "parsley",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Parsley",
        "created_at": "2013-03-19T01:30:27.723Z",
        "updated_at": "2019-02-08T20:39:45.180Z",
        "slug": "parsley",
        "parent_id": null,
        "plantings_count": 58,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 174,
        "median_days_to_first_harvest": null,
        "median_days_to_last_harvest": null
    },
    {
        "id": 60,
        "name": "coriander",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Coriander",
        "created_at": "2013-03-19T01:30:26.078Z",
        "updated_at": "2019-04-10T06:20:25.195Z",
        "slug": "coriander",
        "parent_id": null,
        "plantings_count": 56,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 135,
        "median_days_to_first_harvest": 50,
        "median_days_to_last_harvest": 98
    },
    {
        "id": 164,
        "name": "potato",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Potatoes",
        "created_at": "2013-03-19T01:30:28.480Z",
        "updated_at": "2018-09-08T04:48:29.198Z",
        "slug": "potato",
        "parent_id": null,
        "plantings_count": 56,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 109,
        "median_days_to_first_harvest": 95,
        "median_days_to_last_harvest": 95
    },
    {
        "id": 214,
        "name": "thyme",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Thymus_%28plant%29",
        "created_at": "2013-03-19T01:30:29.989Z",
        "updated_at": "2019-03-26T09:19:19.389Z",
        "slug": "thyme",
        "parent_id": null,
        "plantings_count": 50,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 396,
        "median_days_to_first_harvest": 69,
        "median_days_to_last_harvest": 276
    },
    {
        "id": 172,
        "name": "radish",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Radish",
        "created_at": "2013-03-19T01:30:28.716Z",
        "updated_at": "2018-06-11T00:06:21.065Z",
        "slug": "radish",
        "parent_id": null,
        "plantings_count": 48,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 82,
        "median_days_to_first_harvest": null,
        "median_days_to_last_harvest": null
    },
    {
        "id": 180,
        "name": "rosemary",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Rosemary",
        "created_at": "2013-03-19T01:30:28.897Z",
        "updated_at": "2018-08-07T03:03:35.773Z",
        "slug": "rosemary",
        "parent_id": null,
        "plantings_count": 48,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 218,
        "median_days_to_first_harvest": 419,
        "median_days_to_last_harvest": null
    },
    {
        "id": 15,
        "name": "arugula",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Arugula",
        "created_at": "2013-03-19T01:30:25.140Z",
        "updated_at": "2019-02-08T20:38:34.632Z",
        "slug": "arugula",
        "parent_id": null,
        "plantings_count": 46,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 96,
        "median_days_to_first_harvest": 117,
        "median_days_to_last_harvest": 76
    },
    {
        "id": 76,
        "name": "eggplant",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Eggplant",
        "created_at": "2013-03-19T01:30:26.388Z",
        "updated_at": "2018-06-11T00:10:59.941Z",
        "slug": "eggplant",
        "parent_id": null,
        "plantings_count": 45,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": null,
        "median_days_to_first_harvest": null,
        "median_days_to_last_harvest": null
    },
    {
        "id": 142,
        "name": "oregano",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Oregano",
        "created_at": "2013-03-19T01:30:27.656Z",
        "updated_at": "2019-03-26T09:19:35.648Z",
        "slug": "oregano",
        "parent_id": null,
        "plantings_count": 45,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 343,
        "median_days_to_first_harvest": 49,
        "median_days_to_last_harvest": null
    },
    {
        "id": 187,
        "name": "sage",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Salvia_officinalis",
        "created_at": "2013-03-19T01:30:29.114Z",
        "updated_at": "2018-05-30T15:48:34.445Z",
        "slug": "sage",
        "parent_id": 424,
        "plantings_count": 43,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 269,
        "median_days_to_first_harvest": 131,
        "median_days_to_last_harvest": 233
    },
    {
        "id": 73,
        "name": "dill",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Dill",
        "created_at": "2013-03-19T01:30:26.338Z",
        "updated_at": "2019-01-12T09:39:32.504Z",
        "slug": "dill",
        "parent_id": null,
        "plantings_count": 42,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 116,
        "median_days_to_first_harvest": 50,
        "median_days_to_last_harvest": 57
    },
    {
        "id": 54,
        "name": "chives",
        "en_wikipedia_url": "https://en.wikipedia.org/wiki/Chives",
        "created_at": "2013-03-19T01:30:25.940Z",
        "updated_at": "2019-02-12T08:36:23.376Z",
        "slug": "chives",
        "parent_id": null,
        "plantings_count": 40,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 217,
        "median_days_to_first_harvest": 43,
        "median_days_to_last_harvest": 29
    },
    {
        "id": 131,
        "name": "mint",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Mentha",
        "created_at": "2013-03-19T01:30:27.448Z",
        "updated_at": "2019-04-28T03:52:25.175Z",
        "slug": "mint",
        "parent_id": null,
        "plantings_count": 39,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": true,
        "median_lifespan": 70,
        "median_days_to_first_harvest": null,
        "median_days_to_last_harvest": null
    },
    {
        "id": 397,
        "name": "cherry tomato",
        "en_wikipedia_url": "http://en.wikipedia.org/wiki/Cherry_tomato",
        "created_at": "2014-11-19T06:11:19.187Z",
        "updated_at": "2019-03-09T03:37:44.335Z",
        "slug": "cherry-tomato",
        "parent_id": 216,
        "plantings_count": 38,
        "creator_id": 438,
        "requester_id": null,
        "approval_status": "approved",
        "reason_for_rejection": null,
        "request_notes": null,
        "rejection_notes": null,
        "perennial": false,
        "median_lifespan": 126,
        "median_days_to_first_harvest": 66,
        "median_days_to_last_harvest": 133
    }
]

export default imageData